#pragma once


#include <fstream>
#include <vector>
#include "obj_io.h"

#define CHECK_CUDA_ERROR(err) \
    if (err != cudaSuccess) { \
        printf("CUDA Error: %s (line: %d)\n", cudaGetErrorString(err), __LINE__); \
        exit(1); \
    }

struct vertex_s {
    float3 position{};
    float3 normal{};
    float2 uv{};
};

struct face_s {
    vertex_s vertices[3]{};
    float reflectivity{};
    float3 radiosity{};
    float3 emission{};
};


inline void SaveFacesToObjWithMaterial(
    const face_s *faces,
    size_t faces_count,
    const char *obj_filename,
    const char *mtl_filename
) {
    // Write MTL file
    std::ofstream mtl_file(mtl_filename);
    if (!mtl_file.is_open()) {
        throw std::runtime_error("Failed to open MTL file for writing");
    }

    mtl_file << "# Material file generated by obj-io\n";

    for (size_t i = 0; i < faces_count; ++i) {
        mtl_file << "newmtl material_" << i << "\n";

        // Kd = diffuse color (using radiosity)
        mtl_file << "Kd " << faces[i].radiosity.x << " "
                << faces[i].radiosity.y << " "
                << faces[i].radiosity.z << "\n";

        // Ke = emission color
        mtl_file << "Ke " << faces[i].emission.x << " "
                << faces[i].emission.y << " "
                << faces[i].emission.z << "\n";

        // Ns = specular exponent (mapped from reflectivity)
        mtl_file << "Ns " << (faces[i].reflectivity * 128.0f) << "\n";
        mtl_file << "\n";
    }
    mtl_file.close();

    // Write OBJ file (referencing MTL)
    std::ofstream ofs(obj_filename, std::ios::binary);
    if (!ofs.is_open()) {
        throw std::runtime_error("Failed to open OBJ file for writing");
    }

    // Write MTL library reference
    ofs << "# Material library\n";
    ofs << "mtllib " << mtl_filename << "\n\n";

    using thinks::WriteObj;
    using thinks::ObjMap;
    using thinks::ObjEnd;
    using thinks::ObjIndex;
    using thinks::ObjTriangleFace;
    using thinks::ObjPosition;
    using thinks::ObjTexCoord;
    using thinks::ObjNormal;

    size_t vertex_count = 0;
    size_t face_index = 0;

    // Position mapper function
    auto position_mapper = [&faces, &vertex_count, faces_count]() {
        size_t current_face_idx = vertex_count / 3;
        size_t vertex_in_face = vertex_count % 3;

        if (current_face_idx >= faces_count) {
            return ObjEnd<ObjPosition<float, 3> >();
        }

        const auto &vertex = faces[current_face_idx].vertices[vertex_in_face];
        vertex_count++;

        return ObjMap(ObjPosition<float, 3>{
            vertex.position.x,
            vertex.position.y,
            vertex.position.z
        });
    };

    // Texture coordinate mapper function
    auto tex_coord_mapper = [&faces, &vertex_count, faces_count]() {
        size_t current_face_idx = vertex_count / 3;
        size_t vertex_in_face = vertex_count % 3;

        if (current_face_idx >= faces_count) {
            return ObjEnd<ObjTexCoord<float, 2> >();
        }

        const auto &vertex = faces[current_face_idx].vertices[vertex_in_face];
        vertex_count++;

        return ObjMap(ObjTexCoord<float, 2>{
            vertex.uv.x,
            vertex.uv.y
        });
    };

    // Normal mapper function
    auto normal_mapper = [&faces, &vertex_count, faces_count]() {
        size_t current_face_idx = vertex_count / 3;
        size_t vertex_in_face = vertex_count % 3;

        if (current_face_idx >= faces_count) {
            return ObjEnd<ObjNormal<float> >();
        }

        const auto &vertex = faces[current_face_idx].vertices[vertex_in_face];
        vertex_count++;

        return ObjMap(ObjNormal<float>{
            vertex.normal.x,
            vertex.normal.y,
            vertex.normal.z
        });
    };

    // Face mapper function
    auto face_mapper = [&face_index, &ofs, faces_count]() {
        if (face_index >= faces_count) {
            return ObjEnd<ObjTriangleFace<ObjIndex<uint32_t> > >();
        }

        // Write material name for this face
        ofs << "usemtl material_" << face_index << "\n";

        uint32_t base_idx = static_cast<uint32_t>(face_index * 3);
        face_index++;

        return ObjMap(ObjTriangleFace<ObjIndex<uint32_t> >{
            ObjIndex<uint32_t>(base_idx),
            ObjIndex<uint32_t>(base_idx + 1),
            ObjIndex<uint32_t>(base_idx + 2)
        });
    };

    auto result = WriteObj(ofs, position_mapper, face_mapper,
                           tex_coord_mapper, normal_mapper);

    if (result.position_count == 0) {
        throw std::runtime_error("Failed to write OBJ file");
    }
}
